{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib.options) mkEnableOption mkOption literalExpression;
  inherit (lib.types)
    attrsOf
    enum
    lines
    listOf
    oneOf
    package
    str
    submodule
    bool
    ;
  inherit (lib.modules) mkIf;

  cfg = config.programs.lazyvim;

  # Import data loading library
  dataLib = import ../lib/data-loading.nix { inherit lib pkgs; };

  pluginsOptionType = listOf (oneOf [
    package
    (submodule {
      options = {
        name = mkOption { type = str; };
        path = mkOption { type = package; };
      };
    })
  ]);

  # Collect enabled extras using data-driven approach
  enabledExtras = dataLib.getEnabledExtras cfg.extras;
  coreDependencyPackages = dataLib.getCoreDependencyPackages;
  autoDependencyPackages = dataLib.getExtraDependencyPackages enabledExtras;

in
{
  options.programs.lazyvim = {
    enable = mkEnableOption "LazyVim";

    neovim = mkOption {
      type = package;
      default = pkgs.neovim;
      defaultText = literalExpression "pkgs.neovim";
      description = "The Neovim package to use. Override to use neovim-nightly or a custom build.";
    };

    configDir = mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = literalExpression "./nvim-config";
      description = ''
        Path to your complete Neovim configuration directory.

        The directory should follow standard Neovim/LazyVim structure:
        ```
        configDir/
        ├── lua/
        │   ├── config/          # LazyVim config files
        │   │   ├── autocmds.lua
        │   │   ├── keymaps.lua
        │   │   ├── lazy.lua
        │   │   └── options.lua
        │   └── plugins/         # Your plugin configurations
        │       └── *.lua
        └── (other files/dirs)
        ```

        All files will be symlinked to `~/.config/nvim/`, EXCEPT:
        - `init.lua` (generated by this module)
        - `lazyvim.json` (generated by LazyVim at runtime and excluded here)

        This allows you to maintain your configuration in version control
        while letting the module handle Nix-specific setup.
      '';
    };

    extraPlugins = mkOption {
      type = pluginsOptionType;
      default = [ ];
      example = literalExpression ''
        with pkgs.vimPlugins; [
          # Custom plugins not in LazyVim
          vim-surround
          vim-repeat

          # Or with explicit naming
          {
            name = "custom-plugin";
            path = pkgs.myCustomPlugin;
          }
        ]
      '';
      description = ''
        Additional vim plugins to make available to LazyVim beyond the core plugins.

        Core LazyVim plugins are automatically loaded from source/plugins.json.
        Use this option only for plugins outside of LazyVim's standard setup.

        These plugins will be symlinked to the dev.path directory so lazy.nvim can find them.
      '';
    };

    cmp = mkOption {
      type = enum [
        "nvim-cmp"
        "blink.cmp"
        "auto"
      ];
      default = "auto";
      description = ''
        Choose the completion engine.
        If you choose "auto", it will use the LazyVim default completion engine.
      '';
    };

    picker = mkOption {
      type = enum [
        "telescope"
        "fzf"
        "snacks"
        "auto"
      ];
      default = "auto";
      description = ''
        Choose the picker engine.
        If you choose "auto", it will use the LazyVim default picker engine.
      '';
    };

    explorer = mkOption {
      type = enum [
        "neo-tree"
        "snacks"
        "auto"
      ];
      default = "auto";
      description = ''
        Choose the file explorer.
        If you choose "auto", it will use the LazyVim default file explorer.
      '';
    };

    extras = mkOption {
      type = attrsOf (
        attrsOf (submodule {
          options = {
            enable = mkEnableOption "this LazyVim extra";

            installDependencies = mkOption {
              type = bool;
              default = false;
              description = ''
                Whether to automatically install mapped system dependencies for this extra.
                This uses `source/dependencies.json` and includes any mapped runtime dependencies.
                Tools without a nixpkgs mapping are skipped; add those manually via `extraPackages`.
              '';
            };
          };
        })
      );
      default = { };
      example = literalExpression ''
        {
          lang.rust.enable = true;
          lang.python = {
            enable = true;
            installDependencies = true;  # Auto-install python LSP, etc.
          };
          editor.dial.enable = true;
          ai.copilot.enable = true;
        }
      '';
      description = ''
        LazyVim extras to enable. Each entry `extras.{category}.{name}.enable = true`
        adds the corresponding LazyVim extra to your configuration.

        Available extras are discovered from LazyVim automatically.
        Run `nix flake show` to see all available extras.
        Update `source/extras.json` when syncing with latest LazyVim extras.
      '';
    };

    finalExtraSpec = mkOption {
      type = lines;
      readOnly = true;
      internal = true;
      description = ''
        Derived Lazy spec snippet used during setup. Automatically generated from enabled `extras`.
      '';
    };

    extraPackages = mkOption {
      type = listOf package;
      default = [ ];
      example = literalExpression ''
        with pkgs; [
          # Language servers
          rust-analyzer
          gopls
          nodePackages.typescript-language-server

          # Formatters
          stylua
          nixfmt-rfc-style

          # Linters
          shellcheck
        ]
      '';
      description = ''
        Additional packages to be made available to LazyVim.
        This should include LSP servers, formatters, linters, and other tools.
      '';
    };
  };

  config = mkIf cfg.enable {
    programs.lazyvim = {
      # Generate final spec directly from enabled extras
      finalExtraSpec = lib.concatMapStrings (extra: ''
        { import = "${extra.import}" },
      '') enabledExtras;

      # Add core LazyVim dependencies
      extraPackages = coreDependencyPackages ++ autoDependencyPackages;
    };

    # Configure XDG files
    xdg.configFile =
      if cfg.configDir == null then
        { }
      else
        let
          # Copy configDir into the store while excluding files generated at activation time.
          filteredConfig = pkgs.runCommand "filtered-nvim-config" { } ''
            mkdir -p $out
            cd ${cfg.configDir}

            for item in *; do
              if [[ "$item" != "init.lua" ]] && \
                 [[ "$item" != "lazyvim.json" ]]; then
                cp -r "$item" $out/
              fi
            done
          '';
        in
        {
          "nvim" = {
            source = filteredConfig;
            recursive = true;
          };
        };

    # Configure Neovim with LazyVim
    programs.neovim = {
      enable = true;
      package = cfg.neovim;
      extraPackages = lib.unique cfg.extraPackages;

      withNodeJs = false;
      withRuby = false;

      viAlias = true;
      vimAlias = true;
      vimdiffAlias = true;

      plugins = with pkgs.vimPlugins; [ lazy-nvim ];

      initLua =
        let
          mkEntryFromDrv =
            drv:
            if lib.isDerivation drv then
              {
                name = lib.getName drv;
                path = drv;
              }
            else
              drv;

          # Load core plugins from data and combine with user's extraPlugins
          allPlugins = dataLib.getCorePlugins ++ cfg.extraPlugins;

          lazyvimPlugins = pkgs.linkFarm "lazy-plugins" (builtins.map mkEntryFromDrv allPlugins);
        in
        ''
          local uv = vim.uv or vim.loop
          local function path_exists(path)
            return type(path) == "string" and uv.fs_stat(path) ~= nil
          end

          local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
          local has_lazy = path_exists(lazypath)

          if not has_lazy then
            local fallback_patterns = {
              vim.env.LAZY_NVIM_PATH,
              vim.fn.stdpath("config") .. "/lazy.nvim",
              "/nix/store/*-lazy.nvim-*",
              "/nix/store/*-vimplugin-lazy.nvim-*",
            }

            for _, pattern in ipairs(fallback_patterns) do
              if type(pattern) == "string" and pattern ~= "" then
                if pattern:find("%*") then
                  local matches = vim.fn.glob(pattern, true, true)
                  if type(matches) == "string" then
                    matches = { matches }
                  end
                  for _, match in ipairs(matches) do
                    if path_exists(match) then
                      lazypath = match
                      has_lazy = true
                      break
                    end
                  end
                elseif path_exists(pattern) then
                  lazypath = pattern
                  has_lazy = true
                end
              end
              if has_lazy then
                break
              end
            end
          end

          if not has_lazy then
            local repo = "https://github.com/folke/lazy.nvim.git"
            vim.fn.system({ "git", "clone", "--filter=blob:none", repo, lazypath })
            has_lazy = path_exists(lazypath)
          end

          if not has_lazy then
            vim.api.nvim_err_writeln("lazy.nvim not found; install it or update your configuration.")
            return
          end

          vim.opt.rtp:prepend(lazypath)
          vim.g.lazyvim_cmp = "${cfg.cmp}"
          vim.g.lazyvim_picker = "${cfg.picker}"
          vim.g.lazyvim_explorer = "${cfg.explorer}"
          vim.g.lazyvim_check_order = false

          require("lazy").setup({
            change_detection = { notify = false },
            defaults = {
              lazy = true,
              version = false
            },
            ui = { border = "rounded" },
            dev = {
              path = "${lazyvimPlugins}",
              patterns = { "" },
              fallback = true,
            },
            checker = { enabled = false },
            rocks = { enabled = false },
            performance = {
              cache = { enabled = true },
              rtp = {
                disabled_plugins = {
                  "gzip",
                  "tarPlugin",
                  "tohtml",
                  "tutor",
                  "zipPlugin",
                },
              },
            },
            spec = {
              { "LazyVim/LazyVim", import = "lazyvim.plugins" },
              ${cfg.finalExtraSpec}
              { import = "plugins" },
              -- The following configs are needed for fixing lazyvim on nix
              -- disable mason.nvim, use programs.lazyvim.extraPackages
              { "mason-org/mason-lspconfig.nvim", enabled = false },
              { "mason-org/mason.nvim", enabled = false },
              -- treesitter ships with all grammars via overlay; keep ensure_installed empty to skip downloads
              { "nvim-treesitter/nvim-treesitter", opts = function(_, opts) opts.ensure_installed = {} end },
            },
          })
        '';
    };
  };
}
