{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib.options) mkEnableOption mkOption literalExpression;
  inherit (lib.types)
    attrsOf
    enum
    listOf
    oneOf
    package
    str
    submodule
    bool
    ;
  inherit (lib.modules) mkIf;

  cfg = config.programs.lazyvim;

  # Import data loading library
  dataLib = import ./lib/data-loading.nix { inherit lib pkgs; };

  pluginsOptionType = listOf (oneOf [
    package
    (submodule {
      options = {
        name = mkOption { type = str; };
        path = mkOption { type = package; };
      };
    })
  ]);

  # Collect enabled extras using data-driven approach
  enabledExtras = dataLib.getEnabledExtras cfg.extras;
  selectorPluginExtras =
    (lib.optional (cfg.cmp == "nvim-cmp") (dataLib.requireExtraMetadata "coding" "nvim-cmp"))
    ++ (lib.optional (cfg.cmp == "blink.cmp" || cfg.cmp == "auto") (
      dataLib.requireExtraMetadata "coding" "blink"
    ))
    ++ (lib.optional (cfg.picker == "telescope") (dataLib.requireExtraMetadata "editor" "telescope"))
    ++ (lib.optional (cfg.picker == "fzf") (dataLib.requireExtraMetadata "editor" "fzf"))
    ++ (lib.optional (cfg.picker == "snacks") (dataLib.requireExtraMetadata "editor" "snacks_picker"))
    ++ (lib.optional (cfg.explorer == "neo-tree") (dataLib.requireExtraMetadata "editor" "neo-tree"))
    ++ (lib.optional (cfg.explorer == "snacks") (
      dataLib.requireExtraMetadata "editor" "snacks_explorer"
    ));
  metadataPluginExtras = enabledExtras ++ selectorPluginExtras;
  coreDependencyPackages = dataLib.getCoreDependencyPackages;
  autoDependencyPackages = dataLib.getExtraDependencyPackages enabledExtras;
  extraPluginPackages = dataLib.getExtraPluginPackages {
    extras = metadataPluginExtras;
    inherit (cfg) cmp;
  };
  excludedPluginPackages = dataLib.getExcludedPluginPackages {
    extras = metadataPluginExtras;
    inherit (cfg) cmp;
  };

in
{
  options.programs.lazyvim = {
    enable = mkEnableOption "LazyVim";

    neovim = mkOption {
      type = package;
      default = pkgs.neovim;
      defaultText = literalExpression "pkgs.neovim";
      description = "The Neovim package to use. Override to use neovim-nightly or a custom build.";
    };

    appName = mkOption {
      type = str;
      default = "nvim";
      example = "lazyvim";
      description = ''
        The app name used for Neovim's `NVIM_APPNAME`.
        This determines the config directory under `~/.config/`
        (for example, `"lazyvim"` uses `~/.config/lazyvim/`).
      '';
    };

    configDir = mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      example = literalExpression "./nvim-config";
      description = ''
        Path to your complete Neovim configuration directory.

        The directory should follow standard Neovim/LazyVim structure:
        ```
        configDir/
        ├── lua/
        │   ├── config/          # LazyVim config files
        │   │   ├── autocmds.lua
        │   │   ├── keymaps.lua
        │   │   ├── lazy.lua
        │   │   └── options.lua
        │   └── plugins/         # Your plugin configurations
        │       └── *.lua
        └── (other files/dirs)
        ```

        All files will be symlinked to `~/.config/<appName>/`, where `<appName>`
        is `programs.lazyvim.appName` (default: `nvim`), EXCEPT:
        - `init.lua` (generated by this module)
        - `lazyvim.json` (generated by LazyVim at runtime and excluded here)

        This allows you to maintain your configuration in version control
        while letting the module handle Nix-specific setup.
      '';
    };

    extraPlugins = mkOption {
      type = pluginsOptionType;
      default = [ ];
      example = literalExpression ''
        with pkgs.vimPlugins; [
          # Custom plugins not in LazyVim
          vim-surround
          vim-repeat

          # Or with explicit naming
          {
            name = "custom-plugin";
            path = pkgs.myCustomPlugin;
          }
        ]
      '';
      description = ''
        Additional vim plugins to make available to LazyVim beyond the core plugins.

        Core LazyVim plugins are automatically loaded from source/plugins.json.
        Use this option only for plugins outside of LazyVim's standard setup.

        These plugins will be symlinked to the dev.path directory so lazy.nvim can find them.
      '';
    };

    excludePlugins = mkOption {
      type = pluginsOptionType;
      default = [ ];
      example = literalExpression ''
        with pkgs.vimPlugins; [
          fzf-lua
        ]
      '';
      description = ''
        Core or metadata-provided vim plugins to omit from the lazy.nvim dev path.

        This is mainly useful when you want to replace a default engine with a different one.
      '';
    };

    cmp = mkOption {
      type = enum [
        "nvim-cmp"
        "blink.cmp"
        "auto"
      ];
      default = "auto";
      description = ''
        Choose the completion engine.
        If you choose "auto", it will use the LazyVim default completion engine.
      '';
    };

    picker = mkOption {
      type = enum [
        "telescope"
        "fzf"
        "snacks"
        "auto"
      ];
      default = "auto";
      description = ''
        Choose the picker engine.
        If you choose "auto", it will use the LazyVim default picker engine.
      '';
    };

    explorer = mkOption {
      type = enum [
        "neo-tree"
        "snacks"
        "auto"
      ];
      default = "auto";
      description = ''
        Choose the file explorer.
        If you choose "auto", it will use the LazyVim default file explorer.
      '';
    };

    installDependencies = mkOption {
      type = bool;
      default = false;
      description = ''
        Whether enabled extras should install their mapped system dependencies by default.

        This uses `source/dependencies.json` and includes any mapped runtime dependencies.
        Individual extras can override this via `extras.<category>.<name>.installDependencies`.
      '';
    };

    extras = mkOption {
      type = attrsOf (
        attrsOf (submodule {
          options = {
            enable = mkEnableOption "this LazyVim extra";

            installDependencies = mkOption {
              type = bool;
              default = cfg.installDependencies;
              description = ''
                Whether to automatically install mapped system dependencies for this extra.
                This uses `source/dependencies.json` and includes any mapped runtime dependencies.
                Tools without a nixpkgs mapping are skipped; add those manually via `extraPackages`.
                Defaults to `programs.lazyvim.installDependencies`.
              '';
            };
          };
        })
      );
      default = { };
      example = literalExpression ''
        {
          lang.rust.enable = true;
          lang.python = {
            enable = true;
            installDependencies = false; # Override the top-level default for this extra
          };
          editor.dial.enable = true;
          ai.copilot.enable = true;
        }
      '';
      description = ''
        LazyVim extras to enable. Each entry `extras.{category}.{name}.enable = true`
        adds the corresponding LazyVim extra to your configuration.

        Available extras are discovered from LazyVim automatically.
        Run `nix flake show` to see all available extras.
        Update `source/extras.json` when syncing with latest LazyVim extras.
      '';
    };

    extraPackages = mkOption {
      type = listOf package;
      default = [ ];
      example = literalExpression ''
        with pkgs; [
          # Language servers
          rust-analyzer
          gopls
          typescript-language-server

          # Formatters
          stylua
          nixfmt-rfc-style

          # Linters
          shellcheck
        ]
      '';
      description = ''
        Additional packages to be made available to LazyVim.
        This should include LSP servers, formatters, linters, and other tools.
      '';
    };
  };

  config = mkIf cfg.enable (
    let
      mkEntryFromDrv =
        drv:
        if lib.isDerivation drv then
          {
            name = "${lib.getName drv}";
            path = drv;
          }
        else
          drv;

      # Remove excluded defaults, then add metadata-driven and user-defined plugins.
      allPlugins =
        lib.subtractLists (excludedPluginPackages ++ cfg.excludePlugins) dataLib.getCorePlugins
        ++ extraPluginPackages
        ++ cfg.extraPlugins;

      lazyvimPlugins = pkgs.linkFarm "lazy-plugins" (builtins.map mkEntryFromDrv allPlugins);
      extraImportSpec = lib.concatMapStrings (extra: ''
        { import = "${extra.import}" },
      '') enabledExtras;

      generatedInitLua = ''
        local lazypath = ${builtins.toJSON (toString pkgs.vimPlugins.lazy-nvim)}
        vim.opt.rtp:prepend(lazypath)
        vim.g.lazyvim_cmp = "${cfg.cmp}"
        vim.g.lazyvim_picker = "${cfg.picker}"
        vim.g.lazyvim_explorer = "${cfg.explorer}"
        vim.g.lazyvim_check_order = false

        require("lazy").setup({
          change_detection = { notify = false },
          defaults = {
            lazy = true,
            version = false
          },
          ui = { border = "rounded" },
          dev = {
            path = "${lazyvimPlugins}",
            patterns = { "" },
            fallback = true,
          },
          checker = { enabled = false },
          rocks = { enabled = false },
          performance = {
            cache = { enabled = true },
            rtp = {
              disabled_plugins = {
                "gzip",
                "tarPlugin",
                "tohtml",
                "tutor",
                "zipPlugin",
              },
            },
          },
          spec = {
            { "LazyVim/LazyVim", import = "lazyvim.plugins" },
            ${extraImportSpec}
            { import = "plugins" },
            -- The following configs are needed for fixing lazyvim on nix
            -- disable mason.nvim, use programs.lazyvim.extraPackages
            { "jay-babu/mason-nvim-dap.nvim", enabled = false },
            { "mason-org/mason-lspconfig.nvim", enabled = false },
            { "mason-org/mason.nvim", enabled = false },
            -- treesitter ships with all grammars via overlay; keep ensure_installed empty to skip downloads
            { "nvim-treesitter/nvim-treesitter", opts = function(_, opts) opts.ensure_installed = {} end },
          },
        })
      '';

      filteredConfig =
        if cfg.configDir == null then
          null
        else
          pkgs.runCommand (lib.strings.sanitizeDerivationName "filtered-${cfg.appName}-config") { } ''
            mkdir -p $out
            cd ${cfg.configDir}

            for item in *; do
              if [[ "$item" != "init.lua" ]] && \
                 [[ "$item" != "lazyvim.json" ]]; then
                cp -r "$item" $out/
              fi
            done
          '';

      wrappedNeovim =
        if cfg.appName == "nvim" then
          cfg.neovim
        else
          pkgs.symlinkJoin {
            name = "${cfg.appName}-neovim";
            paths = [ cfg.neovim ];
            nativeBuildInputs = [ pkgs.makeWrapper ];
            postBuild = ''
              wrapProgram $out/bin/nvim --set NVIM_APPNAME ${lib.escapeShellArg cfg.appName}
            '';
          };
    in
    {
      programs.lazyvim = {
        # Add core LazyVim dependencies
        extraPackages = coreDependencyPackages ++ autoDependencyPackages;
      };

      # Configure XDG files
      xdg.configFile =
        (lib.optionalAttrs (filteredConfig != null) {
          "${cfg.appName}" = {
            source = filteredConfig;
            recursive = true;
          };
        })
        // {
          "${cfg.appName}/init.lua".text = generatedInitLua;
        };

      # Configure Neovim with LazyVim
      programs.neovim = {
        enable = true;
        package = wrappedNeovim;
        extraPackages = lib.unique cfg.extraPackages;

        withNodeJs = false;
        withRuby = false;

        viAlias = true;
        vimAlias = true;
        vimdiffAlias = true;

        plugins = with pkgs.vimPlugins; [ lazy-nvim ];
      };
    }
  );
}
